import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, KeyRound, Plus, ShieldCheck, Trash2 } from 'lucide-react'
import { signingKeysApi, type SigningKey, type SigningKeyState } from '../api/client'
import { useAuth } from '../hooks/useAuth'
import { Badge } from '../components/ui/Badge'
import { Button } from '../components/ui/Button'
import { Dialog } from '../components/ui/Dialog'
import { EmptyState } from '../components/ui/EmptyState'
import { Input } from '../components/ui/Input'
import { Skeleton } from '../components/ui/Skeleton'
import { useToast } from '../components/ui/Toast'

function stateColor(state: SigningKeyState): 'green' | 'yellow' | 'red' | 'blue' { return state === 'ACTIVE' || state === 'VERIFICATION_ONLY' ? 'green' : state === 'STAGED' ? 'yellow' : 'red' }
function stateLabel(state: SigningKeyState): string { return state === 'VERIFICATION_ONLY' ? 'verification overlap' : state.toLowerCase() }
function denied(error: unknown): boolean { return error instanceof Error && /403|forbidden|denied|not authorized/i.test(error.message) }
function time(value?: string): string { return value ? new Date(value).toLocaleString() : '—' }
function Info({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-medium uppercase tracking-wide text-ink-500">{label}</dt><dd className="mt-1 break-words text-sm text-ink-900">{value}</dd></div> }

function EmergencyDialog({ keyItem, tenantId, onClose, onDone }: { keyItem: SigningKey; tenantId: string; onClose: () => void; onDone: () => void }) {
  const { toast } = useToast()
  const [confirmation, setConfirmation] = useState('')
  const [acknowledged, setAcknowledged] = useState(false)
  const emergency = useMutation({ mutationFn: () => signingKeysApi.emergencyRetire(tenantId, keyItem.id), onSuccess: () => { onDone(); onClose(); toast('success', 'Signing key emergency-retired') }, onError: (error: Error) => toast('error', error.message) })
  return <Dialog open onClose={onClose} title="Emergency retire signing key" description="This bypasses the normal verification-overlap safety guardrail and may invalidate active sessions immediately."><form className="space-y-4" onSubmit={event => { event.preventDefault(); emergency.mutate() }}><div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-900"><p className="font-semibold">Key: {keyItem.kid}</p><p className="mt-1">Use this only for a confirmed key compromise or equivalent incident.</p></div><label className="flex items-start gap-2 text-sm text-ink-700"><input type="checkbox" required checked={acknowledged} onChange={event => setAcknowledged(event.target.checked)} className="mt-0.5 rounded border-line text-red-700 focus:ring-red-300" />I understand this can invalidate currently issued tokens.</label><Input label="Type EMERGENCY RETIRE to continue" required value={confirmation} onChange={event => setConfirmation(event.target.value)} autoComplete="off" /><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={onClose}>Cancel</Button><Button type="submit" variant="danger" loading={emergency.isPending} disabled={confirmation !== 'EMERGENCY RETIRE' || !acknowledged}>Emergency retire</Button></div></form></Dialog>
}

function KeyDetails({ keyItem, tenantId, onChanged }: { keyItem: SigningKey; tenantId: string; onChanged: () => void }) {
  const { toast } = useToast()
  const [emergencyOpen, setEmergencyOpen] = useState(false)
  const activate = useMutation({ mutationFn: () => signingKeysApi.activate(tenantId, keyItem.id), onSuccess: () => { onChanged(); toast('success', 'Signing key activated') }, onError: (error: Error) => toast('error', error.message) })
  const retire = useMutation({ mutationFn: () => signingKeysApi.retire(tenantId, keyItem.id), onSuccess: () => { onChanged(); toast('success', 'Signing key retired') }, onError: (error: Error) => toast('error', error.message) })
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-4 border-b border-line pb-5"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold text-ink-900">{keyItem.kid}</h2><Badge color={stateColor(keyItem.state)}>{stateLabel(keyItem.state)}</Badge></div><p className="mt-1 text-sm text-ink-500">Axiom identity signing key · revision {keyItem.revision}</p></div><div className="flex flex-wrap gap-2">{keyItem.state === 'STAGED' && <Button size="sm" loading={activate.isPending} onClick={() => { if (window.confirm(`Activate signing key ${keyItem.kid}? The current active key will enter verification overlap.`)) activate.mutate() }}><CheckCircle2 size={14} /> Activate</Button>}{keyItem.state !== 'RETIRED' && <a href="/identity-controls" className="rounded-md border border-line px-3 py-2 text-sm font-medium text-ink-700 hover:bg-slate-50">Request key retirement</a>}</div></div><div className="rounded-md border border-axiom-200 bg-axiom-50 px-4 py-3 text-sm text-axiom-900">Private key material is never displayed. Retirement requests must go through Identity Controls.</div><section className="surface-card p-5"><h3 className="font-semibold text-ink-900">Lifecycle</h3><dl className="mt-4 grid gap-4 sm:grid-cols-2"><Info label="Key ID (kid)" value={keyItem.kid} /><Info label="Algorithm" value={keyItem.algorithm} /><Info label="State" value={stateLabel(keyItem.state)} /><Info label="Created" value={time(keyItem.createdAt)} /><Info label="Activated" value={time(keyItem.activatedAt)} /><Info label="Verification overlap until" value={time(keyItem.verificationExpiresAt)} /><Info label="Retired" value={time(keyItem.retiredAt)} /><Info label="Record revision" value={String(keyItem.revision)} /></dl></section>{keyItem.state === 'ACTIVE' && <p className="text-sm text-ink-500">Normal retirement is protected while this key is active. Use Identity Controls for a reviewed retirement request.</p>}{keyItem.state === 'VERIFICATION_ONLY' && <p className="text-sm text-ink-500">This key remains available for verification until the overlap window expires. Normal retirement may be rejected until then.</p>}</div>
}

export function SigningKeys() {
  const { user } = useAuth()
  const { toast } = useToast()
  const qc = useQueryClient()
  const tenantId = user?.tenantId || ''
  const [selectedId, setSelectedId] = useState<string | null>(null)
  const keys = useQuery({ queryKey: ['signing-keys', tenantId], queryFn: () => signingKeysApi.list(tenantId), enabled: Boolean(tenantId), retry: false })
  const list = keys.data ?? []
  const selected = list.find(key => key.id === selectedId) ?? list[0]
  const create = useMutation({ mutationFn: () => signingKeysApi.createStaged(tenantId), onSuccess: result => { qc.invalidateQueries({ queryKey: ['signing-keys', tenantId] }); setSelectedId(result.id); toast('success', 'Staged signing key created') }, onError: (error: Error) => toast('error', error.message) })
  function changed() { void qc.invalidateQueries({ queryKey: ['signing-keys', tenantId] }) }
  return <div className="page-shell w-full"><header className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><p className="page-kicker">Identity platform operations</p><h1 className="mt-1 text-2xl font-semibold tracking-tight text-ink-900">Signing keys</h1><p className="mt-1 max-w-2xl text-sm leading-6 text-ink-500">Manage the public lifecycle of Axiom identity signing keys. Private key material is never available in the Admin console.</p></div><Button onClick={() => create.mutate()} loading={create.isPending} disabled={!tenantId}><Plus size={15} /> Create staged key</Button></header>{!tenantId ? <EmptyState icon={<ShieldCheck size={40} className="text-slate-300" />} title="Tenant context unavailable" description="Signing-key operations require an authenticated tenant context." /> : keys.isLoading ? <div className="grid gap-4 lg:grid-cols-2"><Skeleton className="h-44 rounded-lg" /><Skeleton className="h-44 rounded-lg" /></div> : keys.isError ? <EmptyState icon={<KeyRound size={40} className="text-red-300" />} title={denied(keys.error) ? 'Signing keys unavailable' : 'Could not load signing keys'} description={denied(keys.error) ? 'Your signed-in role cannot view signing-key metadata.' : (keys.error as Error).message} /> : list.length === 0 ? <EmptyState icon={<KeyRound size={40} className="text-slate-300" />} title="No signing keys" description="Create a staged key to begin a controlled identity-signing rotation." action={{ label: 'Create staged key', onClick: () => create.mutate() }} /> : <div className="grid gap-4 lg:grid-cols-[minmax(18rem,0.75fr)_minmax(0,1.65fr)]"><section aria-label="Signing keys" className="space-y-3">{list.map(key => <button key={key.id} type="button" onClick={() => setSelectedId(key.id)} className={`surface-card w-full p-5 text-left transition-colors ${selected?.id === key.id ? 'border-axiom-700 ring-2 ring-gold-300/60' : 'hover:border-axiom-300'}`}><div className="flex items-start justify-between gap-3"><div><h2 className="font-mono text-sm font-semibold text-ink-900">{key.kid}</h2><p className="mt-1 text-xs text-ink-500">{key.algorithm} · revision {key.revision}</p></div><Badge color={stateColor(key.state)}>{stateLabel(key.state)}</Badge></div><p className="mt-4 text-xs text-ink-500">Created {time(key.createdAt)}</p></button>)}</section><section className="surface-card min-h-[32rem] p-6">{selected ? <KeyDetails key={selected.id} keyItem={selected} tenantId={tenantId} onChanged={changed} /> : <EmptyState icon={<KeyRound size={40} className="text-slate-300" />} title="Select a signing key" description="Open a key to inspect lifecycle metadata and safe actions." />}</section></div>}</div>
}
