apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom.fullname" . }}
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "axiom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.service.serverPort }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "axiom.fullname" . }}-admin
  labels:
    {{- include "axiom.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  selector:
    {{- include "axiom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
  ports:
    - name: http
      port: {{ .Values.service.adminPort }}
      targetPort: http
      protocol: TCP
